"""The image-triage manifest catalogs every image reference in the corpus.

assets/image-triage.yml is generated by scripts/inventory_images.py and must
stay in sync with the essays: every <img src> and <a>-to-image link present,
each classified, owned ones resolving to a real local file.
"""
import yaml

import inventory_images as inv

ALLOWED_KIND = {"local", "wp", "external", "malformed"}
ALLOWED_DISPOSITION = {"", "own", "generate", "redraw", "drop"}


def _manifest(root):
    return yaml.safe_load((root / "assets" / "image-triage.yml").read_text(encoding="utf-8"))


def test_manifest_exists_and_loads(root):
    data = _manifest(root)
    assert isinstance(data, dict) and data.get("images"), "manifest missing or empty"


def test_manifest_covers_every_image_ref(root):
    data = _manifest(root)
    in_manifest = {(r["essay"], r["src"]) for r in data["images"]}
    in_corpus = {(r["essay"], r["src"]) for r in inv.image_refs()}
    assert in_manifest == in_corpus, (
        f"not catalogued: {sorted(in_corpus - in_manifest)[:5]}; "
        f"orphans: {sorted(in_manifest - in_corpus)[:5]}"
    )


def test_rows_well_formed(root):
    problems = {}
    for r in _manifest(root)["images"]:
        if r.get("kind") not in ALLOWED_KIND:
            problems[r.get("src")] = f"bad kind {r.get('kind')!r}"
        elif r.get("disposition", "") not in ALLOWED_DISPOSITION:
            problems[r.get("src")] = f"bad disposition {r.get('disposition')!r}"
        elif not r.get("essay") or not r.get("type"):
            problems[r.get("src")] = "missing essay/type"
    assert not problems, problems


def test_local_matches_exist(root):
    missing = [r["local_match"] for r in _manifest(root)["images"]
               if r.get("local_match") and not (root / "assets" / r["local_match"]).exists()]
    assert not missing, f"local_match files absent from assets/: {missing}"


def test_manifest_in_sync():
    assert inv.is_in_sync(), "image-triage.yml is stale — run scripts/inventory_images.py"


def test_html_view_has_a_card_per_image():
    images = inv.build_images(inv.image_refs(), inv._load_dispositions())
    page = inv.render_html(images)
    assert "<!DOCTYPE html>" in page
    assert page.count('class="card"') == len(images), "one card per image reference"
    # the disposition of each image must be shown so the page is decision-ready
    assert 'data-disp=' in page
