#!/usr/bin/env python3
"""Inventory every image reference in the essays and emit a triage manifest.

Scans ``<img src>`` and ``<a href>`` image links in essay bodies and classifies
each reference:

- ``local``     — already lives in ``assets/`` (owned, resolved)
- ``wp``        — an owned WordPress upload (``wp-content/uploads/...``), often
                  with a copy already in ``assets/`` (see ``local_match``)
- ``external``  — hosted elsewhere (xkcd, flickr, wikimedia, ...) — not owned
- ``malformed`` — a broken/typo URL (e.g. ``staticfliccom``)

Writes ``assets/image-triage.yml`` with a ``disposition`` per image
(``own | generate | redraw | drop``) for a human to fill in. Owned images
(``local``, or ``wp`` with a local copy) default to ``own``; everything else
starts blank for a case-by-case decision. Re-running preserves human-entered
dispositions and refreshes the rest. ``--check-only`` exits 1 if stale.
"""
import argparse
import glob
import os
import re
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
META = {"README.md", "AGENTS.md", "CLAUDE.md", "ROADMAP.md", "index.md"}
MANIFEST = os.path.join(ROOT, "assets", "image-triage.yml")
IMG_EXT = (".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".bmp")
MALFORMED = ("staticfliccom", "static.flickr.com")
HEADER = (
    "# Image triage manifest — auto-generated by scripts/inventory_images.py.\n"
    "# Fill `disposition` per image: own | generate | redraw | drop.\n"
    "# Owned images default to `own`; re-running preserves your edits.\n"
)


def _body(path):
    m = re.match(r"^---\n.*?\n---\n(.*)$", open(path, encoding="utf-8").read(), re.S)
    return m.group(1) if m else ""


def _assets():
    return {os.path.basename(p) for p in glob.glob(os.path.join(ROOT, "assets", "*"))
            if os.path.isfile(p)}


def _classify(src, assets):
    host_m = re.match(r"https?://([^/]+)", src)
    host = host_m.group(1) if host_m else ""
    if any(b in src for b in MALFORMED):
        kind = "malformed"
    elif re.match(r"(\.\.?/)*assets/", src):
        kind = "local"
    elif "wp-content/uploads" in src:
        kind = "wp"
    elif host:
        kind = "external"
    else:
        kind = "malformed"  # non-http, non-asset, unrecognized shape
    base = os.path.basename(src.split("?")[0])
    local_match = base if base in assets else ""
    return kind, host, local_match


def image_refs():
    """Ordered list of every image reference (auto-derived fields only)."""
    assets = _assets()
    rows = []
    for path in sorted(glob.glob(os.path.join(ROOT, "*.md"))):
        name = os.path.basename(path)
        if name in META:
            continue
        body = _body(path)
        refs = []
        for m in re.finditer(r'<img\b[^>]*\bsrc="([^"]*)"[^>]*>', body):
            alt = re.search(r'\balt="([^"]*)"', m.group(0))
            refs.append(("img", m.group(1), alt.group(1) if alt else ""))
        for m in re.finditer(r'<a\b[^>]*\bhref="([^"]*)"', body):
            url = m.group(1)
            if url.lower().split("?")[0].endswith(IMG_EXT):
                refs.append(("link", url, ""))
        for typ, src, alt in refs:
            kind, host, local_match = _classify(src, assets)
            rows.append({"essay": name, "type": typ, "kind": kind, "host": host,
                         "src": src, "local_match": local_match, "alt": alt})
    return rows


def _default_disposition(row):
    if row["kind"] == "local" or (row["kind"] == "wp" and row["local_match"]):
        return "own"
    return ""


def _load_dispositions():
    if not os.path.exists(MANIFEST):
        return {}
    data = yaml.safe_load(open(MANIFEST, encoding="utf-8")) or {}
    return {(r["essay"], r["src"], r["type"]): r.get("disposition", "")
            for r in data.get("images", [])}


def render(rows, dispositions):
    images = []
    for r in rows:
        disp = dispositions.get((r["essay"], r["src"], r["type"]))
        if disp is None:
            disp = _default_disposition(r)
        images.append({"essay": r["essay"], "type": r["type"], "kind": r["kind"],
                       "host": r["host"], "src": r["src"],
                       "local_match": r["local_match"], "alt": r["alt"],
                       "disposition": disp})
    body = yaml.safe_dump({"images": images}, sort_keys=False, allow_unicode=True,
                          default_flow_style=False, width=4096)
    return HEADER + body


def is_in_sync():
    if not os.path.exists(MANIFEST):
        return False
    return open(MANIFEST, encoding="utf-8").read() == render(image_refs(), _load_dispositions())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check-only", action="store_true")
    args = ap.parse_args()
    rows = image_refs()
    text = render(rows, _load_dispositions())

    from collections import Counter
    kinds = Counter(r["kind"] for r in rows)
    todo = sum(1 for r in rows if _default_disposition(r) == "" and
               (r["essay"], r["src"], r["type"]) not in _load_dispositions())

    if args.check_only:
        if is_in_sync():
            print(f"image-triage.yml is current ({len(rows)} refs: {dict(kinds)}).")
        else:
            print("image-triage.yml is STALE — run scripts/inventory_images.py")
            sys.exit(1)
        return

    with open(MANIFEST, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"Wrote {MANIFEST}: {len(rows)} references {dict(kinds)}.")
    print(f"Owned auto-marked `own`; ~{kinds['external'] + kinds['malformed']} "
          f"need a case-by-case disposition.")


if __name__ == "__main__":
    main()
